version: '3'
services:
  mongo:
    image: 'mongo:bionic'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
    networks:
      - reactjs-todo-list_default
    ports: 
      - "27017:27017"
  mongo-express:
    image: 'mongo-express:latest'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'root'
    networks:
      - reactjs-todo-list_default
    ports: 
      - "8081:8081"
  frontend:
    build: ./frontend
    ports: 
      - "3000:3000"
    networks:
      - reactjs-todo-list_default
  backend:
    build: ./backend
    ports: 
      - "3001:3001"
    networks:
      - reactjs-todo-list_default
networks:
  reactjs-todo-list_default:
    driver: bridge